Web form support
datenanfragen/website pull request #1022
Opened 2023-01-27 15:06 UTC by baltpeter

This will finally fix #401.

The PR isn't quite done yet. TODO:

- [ ] In the new generator, the send request modal closes after `finishRequest()` (or, more specifically, after `addRequest()`). I don't know why. This is already not great for emails, but really not good for web forms.
- [ ] Update the company and SVA single pages.
- [ ] Ensure the suggest form works with the new field.
- [ ] Tests

But I'd like to get some feedback on the implementation before I work on those.

2023-02-09 11:29 UTC, baltpeter commented
I have realized that writing tests isn't really possible until we have merged the data PR, so I've deferred that TODO to an issue (#1027).

2023-02-09 12:06 UTC, baltpeter commented
I'm looking into the disappearing modal. The problem is that we're fetching the proceedings in `App.tsx`:

https://github.com/datenanfragen/website/blob/32b118a8b175b00aa41c668e8d060df715292385/src/Components/App/App.tsx#L67

When we `finishRequest()` and thus `addRequest()`, a new proceeding is created and the whole app rerenders, which causes the modal to be thrown away.

The amusing part: The only reason we're fetching the proceedings there is for the "don't worry, we still have the old generator" hint. :D

2023-02-09 12:13 UTC, baltpeter commented
The problem would disappear if we computed the bool we're interested in directly in the `useProceedingsStore()` call like this:

```ts
const hasUsedOldGenerator = useProceedingsStore(
    (state) =>
        !!Object.values(state.proceedings).find(
            (p) => (getGeneratedMessage(p, 'request')?.date || new Date('9999-12-31')) <= new Date('2022-12-05')
        )
);
```

But @zner0L forbade me from doing that (https://github.com/datenanfragen/website/pull/938#discussion_r992287441). Though, to be fair, he already told me to move this to a store function back then and I just didn't listen. :D And if we do as he said, the problem also disappears…

2023-02-09 12:19 UTC, baltpeter commented
This is now ready for merge. It can (and should) be merged before the data changes.

Please rebase merge instead of squashing.

2023-02-09 16:21 UTC, baltpeter commented
Schema issue in data: https://github.com/datenanfragen/data/issues/2099

2023-02-13 17:00 UTC, baltpeter commented on src/Components/Generator/WebformModal.tsx
> +import { IntlProvider, Text } from 'preact-i18n';
It's not. With this new addition, we now have three similar but different instances of this code, there's also the original one in `MailtoDropdown`.

I didn't particularly like this either, but I see no other sensible way. The code is very simple, mostly just the markup of which fields to show with which content. But they all need slightly different versions of that. How would you abstract that?

2023-02-13 17:01 UTC, baltpeter commented on src/Components/Generator/RequestForm.tsx
> +                            media={TRANSPORT_MEDIA.filter((m) => m !== 'webform' || current_company?.webform)}
I don't really understand what you're saying. What allowlist?

2023-02-13 17:06 UTC, baltpeter commented on src/i18n/de.json
> +        "webform-modal-explanation": "Hier kannst Du den Betreff und Text Deiner generierten Anfrage kopieren, um sie in das Web-Formular einzufügen.",
But this translation is only for the advanced generator. It's possible that the user chose to send the request via web form, even though the default was email.

2023-02-13 18:11 UTC, baltpeter commented on src/Components/Generator/TransportMediumChooser.tsx
> +                    {(props.media || TRANSPORT_MEDIA.filter((m) => m !== 'webform')).map((transportMedium) => (
#1023

2023-02-19 03:23 UTC, zner0L requested changes
Ok, I managed to get a test environment going that was at least good enough for testing the UX and all in all I really like it. Still, I have a few notes on it:

- [ ] I think it would be really useful to copy the message text to the clipboard if someone clicks the link to the form, so that you don't have to switch tabs that often. The 1Password Extension does this as well (at least on iPad OS) and I find it really convenient.
- [ ] This is not blocking but maybe we sould mark webform companies in the search as we do with mail/fax only companies as well?
- [ ] In the new generator flow, there definitely needs to be more expanation as to why there is a link to a webform suddenly. I don't think people necessarily expect to go to another website, when they click that button.

Other than these, I am very happy with how this turned out.

2023-02-24 12:40 UTC, baltpeter commented
> I think it would be really useful to copy the message text to the clipboard if someone clicks the link to the form, so that you don't have to switch tabs that often. The 1Password Extension does this as well (at least on iPad OS) and I find it really convenient.

@mal-tee also suggested that (discussion is unfortunately in the Matrix chat, not here). I agree that such a feature would be useful, but I really don't want to just overwrite the user's clipboard. I have opened #1025 to track the discussion.

2023-02-24 12:42 UTC, baltpeter commented
> This is not blocking but maybe we sould mark webform companies in the search as we do with mail/fax only companies as well?

I've opened #1032 to track that. I have no strong opinion on that.

2023-02-24 12:48 UTC, baltpeter commented
> In the new generator flow, there definitely needs to be more expanation as to why there is a link to a webform suddenly. I don't think people necessarily expect to go to another website, when they click that button.

Not sure whether that is a problem specifically for web forms. Maybe I'm wrong but I feel like the explanation for emails isn't exactly better (and neither opening a tab to a web form nor mailto links are exactly common UX paradigms that users expect).

But if you have a suggestion for an explanation, do tell.

2023-02-24 12:51 UTC, baltpeter commented on src/store/proceedings.ts
> +                    state._hasUsedOldGenerator = !!Object.values(state.proceedings).find(
Sure. :D

2023-02-27 14:24 UTC, zner0L approved these changes
Thanks for the changes! I move my last request to an issue as well, so this is good to go.

2023-02-27 14:25 UTC, merged