Cleanup from `webform` support
datenanfragen/website pull request #1038
Opened 2023-03-03 12:25 UTC by baltpeter

2023-03-03 12:41 UTC, mal-tee approved these changes
Thank you!

2023-06-10 11:26 UTC, zner0L requested changes
Looks good, just a small a11y issue.

2023-06-10 11:26 UTC, zner0L commented on src/Components/RequestList.tsx
> +                                                })}>
This should actually also be an `aria-label` (https://www.a11yproject.com/posts/title-attributes/).

2023-06-10 11:26 UTC, zner0L commented on src/Components/RequestList.tsx
>                                              onClick={() => {
Same here. This needs an `aria-label` as well.

2023-06-10 11:26 UTC, zner0L commented on src/Components/RequestList.tsx
>                                              onClick={() => {
I guess an eslint rule would be useful for that.

2023-06-10 11:37 UTC, zner0L approved these changes

2023-06-10 11:53 UTC, merged