WIP: Speed improvements part 2: JS
datenanfragen/website pull request #379
Opened 2020-08-25 19:12 UTC by baltpeter

2020-08-30 22:44 UTC, baltpeter commented
This PR just expanded in scope a little to also improve our error handling a bit. I would have opened a separate PR instead, but this PR modifies the error handler quite a bit, so that wouldn't have made sense…

2020-09-08 16:07 UTC, zner0L requested changes
Thanks a lot!

2020-09-08 17:59 UTC, baltpeter commented on src/error-handler.js
> +    document.body.innerHTML += html;
As far as I remember, innerHTML is actually [faster](https://www.quirksmode.org/dom/innerhtml.html), at least compared to the DOM methods, not sure about Preact.

Either way, I agree this isn't an issue here. Showing an error modal should definitely be an exception that only occurs once in a blue moon and that potentially taking a couple ms longer seems like a reasonable trade-off to me compared to bloating every page load.

2020-09-08 18:01 UTC, baltpeter commented on src/Components/DonationWidget.js
> +window.renderDonationWidget = function () {
That's a pattern I have adopted a while ago. While not necessary in this case, it allows us to export other functions in this file and then import them somewhere else without the render being triggered.

I agree that this is not… clean. From what I saw, we might be able to get rid of that once the JS is built by Hugo using [resources from string](https://gohugo.io/hugo-pipes/resource-from-string/)?

2020-09-08 18:04 UTC, baltpeter commented on src/error-handler.js
> -    const t = require('Utility/i18n').default;
I don't think. We are losing fields and plurals but other than that, I believe `t()` does the exact same thing that I inlined here. It also works directly on the `I18N_DEFINITION`.

Falling back to the English strings is implemented in the Webpack loader.

2020-09-09 18:24 UTC, zner0L submitted a review, later dismissed

2020-09-09 19:03 UTC, zner0L approved these changes

2020-09-09 19:03 UTC, merged