🇺🇳 [Validation]: Added lang attribute to <html> tag for all languages.
datenanfragen/website pull request #381
Opened 2020-08-25 20:27 UTC by rohitjethoe

### Validated html

Added a html lang attribute to the html tag in the right page language with JavaScript.

2020-08-26 15:22 UTC, baltpeter commented
Hi,

thanks for the suggestion!

We will soon move to a new hosting solution that will allow us to have proper per-language 404 pages that don't need JavaScript for the translation (see #207). We will then be able to just add the `lang` attribute to the `<html>` tag directly.

Do you think this can wait until then? Otherwise, I would request some changes and propose a cleaner implementation. I'll leave that up to you. :)

2020-08-26 19:26 UTC, rohitjethoe commented
@baltpeter There isn't any other JavaScript file linked to the 404 page so I think this is currently the cleanest implementation.

2020-08-27 17:06 UTC, baltpeter requested changes

2020-08-27 17:06 UTC, baltpeter commented on static/404.html
> +let htmlSelector = document.querySelector('html');
The region subtag is optional in the language tag (and it's not like we are targeting any specific regional language variant). Thus, we can do without the switch case. That's what I meant by a cleaner implementation. :) In fact, we can simplify the whole thing to one line:

```js
document.documentElement.lang = lang;
```

2020-09-13 20:36 UTC, baltpeter commented
As I mentioned, now that we have moved to another hosting solution, we don't need the hacky 404 implementation anymore. This PR is thus superseded by #398.

2020-09-13 20:36 UTC, closed without merging