Highlight tested and unverified companies in search results and company single pages
datenanfragen/website pull request #451
Opened 2020-10-14 21:53 UTC by baltpeter

This needs to be merged before datenanfragen/data#773.

2020-10-19 18:22 UTC, Sakshamoo17 commented
layouts/company/single.html

2020-10-19 18:23 UTC, Sakshamoo17 commented
layouts/company/single.html
layouts/company/index.html

2020-11-07 12:03 UTC, mal-tee requested changes
Thank you very much! Such a cool feature. I've left a small comment.

2020-11-07 12:03 UTC, mal-tee commented on src/Components/SearchBar.js
> +                                    (d.quality === 'tested'
FF a11y checking tool doesn't like this: 
![grafik](https://user-images.githubusercontent.com/45886910/98440494-53cfb980-20f9-11eb-8543-5d1a17b0f094.png)

2020-11-07 12:22 UTC, baltpeter commented
Interesting. Thanks for checking. The icon really shouldn't be clickable itself. I'll have to look into that.

2020-11-27 16:46 UTC, baltpeter commented
Genuinely not sure how we could fix this. The [documentation for the issue](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard#Clickable_elements_must_be_focusable_and_should_have_interactive_semantics) says that this applies to elements that "can be clicked with a pointing device" and "An element is clickable if it has an `onclick` event handler defined."

The icon doesn't have an `onclick` handler. I didn't find a way to communicate to Firefox that this element isn't clickable (itself). Setting `role="figure"` or `role="img"` doesn't change anything. Neither does setting `pointer-events: none;` (this also breaks the title text, so not an option anyway). Setting `tabindex="0"` on option div (which is actually supposed to be clickable) doesn't help either.

I wasn't even able to get rid of the issue by setting `tabindex="0"` on the icon itself as the issue description suggests (this also isn't actually an option as that would make the accessibility of the search bar worse imo). 

So yeah, no idea what to do here. For reference: axe doesn't complain about that.

2020-11-27 18:11 UTC, mal-tee approved these changes
Thank you for looking into this! Seems more like it's a problem on Firefox' side, especially if axe doesn't complain. I say: Let's merge and recheck this with future FF (and axe) versions.

2020-11-27 18:15 UTC, merged