Add alt tags to images
datenanfragen/website pull request #492
Opened 2020-11-07 12:54 UTC by mal-tee

> Omitting alt altogether indicates that the image is a key part of the content and no textual equivalent is available. Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it’s decoration or a tracking pixel), and that non-visual browsers may omit it from rendering. Visual browsers will also hide the broken image icon if the alt is empty and the image failed to display."

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

2020-11-07 15:15 UTC, mal-tee commented
I've used https://stackoverflow.com/a/11849333 to find the ones from the last commit. We could consider adding such a regex to either the CI or a precommit hook. What do you think @baltpeter? :D

2020-11-08 13:16 UTC, baltpeter reviewed
Thanks. I agree that most of the card icons to the side are purely decorative and don't need an alt text. Not so sure about the other cases. Some of the humaaans (e.g. the one on the 404 page) are pretty prominent. Also, the icons on the verein page are pretty important imo.

2020-11-08 13:16 UTC, baltpeter commented on content/en/verein/transparency.md
> +<a href="https://www.transparency.de/mitmachen/initiative-transparente-zivilgesellschaft/" class="no-link-decoration"><img src="/img/logo-itz.svg" style="float: right; width: 40%; min-width: 200px; p
```suggestion
<a href="https://www.transparency.de/mitmachen/initiative-transparente-zivilgesellschaft/" class="no-link-decoration"><img src="/img/logo-itz.svg" style="float: right; width: 40%; min-width: 200px; padding: 5px;" alt="Logo of the Initiative for a Transparent Civil Society, with the German text “Initiative Transparente Zivilgesellschaft”"></a>
```

2020-11-08 13:17 UTC, baltpeter commented
> I've used [stackoverflow.com/a/11849333](https://stackoverflow.com/a/11849333) to find the ones from the last commit. We could consider adding such a regex to either the CI or a precommit hook. What do you think @baltpeter? :D

I agree that automated checking for a11y issues is a good idea. Not sure about the regex though. I think there are tools that are better suited. Let's start an issue for that.

2020-11-08 15:29 UTC, mal-tee commented on content/de/blog/supervisory-authorities/index.md
> +<img class="offset-image offset-image-right" src="/img/humaaans/question-1.svg" style="height: 350px;" alt="">
Should this humaaan get an alt-tag too?

2020-11-08 15:29 UTC, mal-tee commented on content/de/open-source.md
> +<img id="open-source-humaaan" class="top-left-humaaan" src="/img/humaaans/open-source.svg" alt="">
Should this humaaan get an alt-tag too? If yes, please provide a string. :D

2020-11-08 15:49 UTC, mal-tee commented
Unfortunately, I can't speak French and Portuguese. What should we do about the corresponding alt tags?

2020-11-08 16:10 UTC, baltpeter requested changes

2020-11-08 16:10 UTC, baltpeter commented on src/i18n/de.json
> +        "404-alt": "Eine Person die auf dem 0 eines großen 404-Schildes sitzt. Sie hält ein Buch, in dem eine Seite fehlt.",
```suggestion
        "404-alt": "Eine Person die auf der 0 eines großen 404-Schildes sitzt. Sie hält ein Buch, in dem eine Seite fehlt.",
```

2020-11-08 16:10 UTC, baltpeter commented on src/i18n/en.json
> +        "404-alt": "A person sitting on the 0 of a big 404 sign. They hold a book with a missing page.",
```suggestion
        "404-alt": "A person sitting on the 0 of a big 404 sign. They are holding a book with a missing page.",
```

2020-11-08 16:10 UTC, baltpeter commented on layouts/verein/list.html
> +                    <div class="top-icon" style="font-size: 38px;"><img src="{{ "card-icons/group.svg" | absURL }}" alt="Ein Umrisse von drei Portraits."></div>
```suggestion
                    <div class="top-icon" style="font-size: 38px;"><img src="{{ "card-icons/group.svg" | absURL }}" alt="Umrisse von drei Personen."></div>
```

2020-11-08 16:12 UTC, baltpeter commented
> Unfortunately, I can't speak French and Portuguese. What should we do about the corresponding alt tags?

It's probably best to create an issue for that.

2020-11-08 16:45 UTC, merged