Spanish site
datenanfragen/website pull request #539
Opened 2021-01-25 05:00 UTC by fm

Starting a PR for translated spanish site. Most of the pages are translated. Just missing the sample letters and a few minor updates which I'll do tomorrow. 

@baltpeter `solicituddedatos.es` is still available if you want to secure it while I wrap up the translations

2021-01-25 05:05 UTC, fm commented
Just realized the JSON I downloaded Weblate may not be in the right format... how can we pull the Weblate translations into the correct JSON format for `es.json`?

2021-01-25 23:13 UTC, baltpeter commented
Thank you very much, @fm!

> @baltpeter solicituddedatos.es is still available if you want to secure it while I wrap up the translations

Great, we have now bought that domain. Doesn't currently point anywhere but we have secured it.

> Just realized the JSON I downloaded Weblate may not be in the right format... how can we pull the Weblate translations into the correct JSON format for es.json?

You actually don't need to do that manually, Weblate will send a PR with the changes. That should happen automatically after a day but I have now manually requested a PR and merged the updates in #542. You should be able to just revert the changes to that file on your branch and then rebase on our master to get the updated file.

2021-01-27 10:15 UTC, baltpeter requested changes
Huge thanks once again, @fm—this is great! I have left some comments below. Also, some general notes:

* If you want, feel free to list yourself as an author for the blog posts you have translated. In the future, we will want to have a separate `translators` key but for now, we are simply handling this via the `authors`.
* For the other language versions, we have translated the slugs to make for nicer URLs. This works by setting `slug: "translated-slug"` and then additionally setting `aliases: ["original-english-slug"]` (plus any other aliases). It's fine if you don't want to do that though, as changing that retroactively is probably quite a bit of work.
* I think we should `last_edited` to the current time for the translated posts.
* The PDF templates should be fillable forms. But that is not blocking. I'll put that on my TODO list and submit a separate PR later, after this PR has been merged.
* The `.txt` templates should be human readable, see [here](https://www.datarequests.org/downloads/sample-letter-gdpr-erasure-request-datarequests.org.txt) for example.

2021-01-27 13:28 UTC, fm commented on src/i18n/en.json
> +        "verein-home-card-join-button": "I want to join",
You don't need the dots, hence why I removed them.

2021-01-27 13:29 UTC, fm commented on src/i18n/en.json
> +        "verein-home-card-donate-button": "I want to donate",
You don't need the dots, hence why I removed them.

2021-01-27 13:29 UTC, fm commented on src/i18n/en.json
> +        "home-hero-line-2": "Use it",
You don't need the dots, hence why I removed them.

2021-01-27 17:03 UTC, baltpeter commented on src/i18n/en.json
> +        "home-hero-line-2": "Use it",
I know we don't _need_ them but we prefer to have them. :)

2021-01-27 17:38 UTC, fm commented on src/i18n/en.json
> +        "verein-home-card-donate-button": "I want to donate",
From a UI/UX perspective, the dots look out of place, two with, one without. And adding a dot to the missing entry would not work either. 

<img width="1242" alt="Screen Shot 2021-01-27 at 12 37 59 PM" src="https://user-images.githubusercontent.com/3654256/106030774-7dff9a80-609c-11eb-9707-b39ea27c5bc0.png">

2021-01-28 16:54 UTC, baltpeter commented
Alright, I'll take over now and fix the merge conflicts, update the URLs in the footer and then prepare this for deploying.

2021-01-28 20:27 UTC, baltpeter commented
I have now created the first deploy of the Spanish site. We'll have to wait for the DNS to update to see if everything worked correctly (and I'll need to manually request an SSL certificate once the DNS is updated).

2021-01-29 08:50 UTC, merged