`postcss-url`: Don't inline every image
datenanfragen/website pull request #593
Opened 2021-05-16 15:02 UTC by mal-tee

* The config was broken before.
* This is especially useful for the bg-wave on the homepage.
  Now it's in a separate file, which saves us some KB in the main.css.

2021-08-17 17:44 UTC, zner0L requested changes
Something is not working right. The `wave-bg.svg` gives me a 404 for the [Deploy Preview](https://deploy-preview-593--datenanfragen.netlify.app/).

2021-08-17 17:44 UTC, zner0L commented on postcss.config.js
> -                    url: 'inline',
We still want some assets to be inlined, don't we? I don't know what `postcss-url` normally does in this case, are files that are considered "small enough" inlined?

2022-03-17 20:40 UTC, zner0L commented
@mal-tee Do you mind taking another look at this?

2022-03-18 09:26 UTC, mal-tee commented
Locally it inlines the asterisk for required form fields and the bg-wave is loaded successfully from a file. I don't know why it doesn't work in the CI.

If someone wants to pick up the pieces: Feel free to do so. I won't for the foreseeable future. Sorry.

2023-06-10 22:07 UTC, closed without merging