Closes #504: Fix cut-off 'required' asterisk
datenanfragen/website pull request #602
Opened 2021-05-23 20:03 UTC by baltpeter

The view box of the SVG was not big enough.

Also change font from FiraGO to Arial as, at least for me, FiraGO
isn't available in the SVG and instead replaced by a default font
that looks quite ugly here.
Arial should be available on just about every system and also ensures
that the asterisk has a consistent height and isn't cut off (again)
depending on the default font per system.

2021-05-24 09:58 UTC, mal-tee requested changes
Thank you, but now the asterisk looks cut-off on the top. I checked it in FF, Chrome and Edge.

![image](https://user-images.githubusercontent.com/45886910/119330998-227a9d80-bc87-11eb-9071-61f9c557fa0a.png)

2021-05-24 10:00 UTC, mal-tee commented
It's also not vertically aligned I think? My guess: Both is due to the fact that the asterisk char is in superscript?

2021-05-24 13:54 UTC, baltpeter commented
Interesting. Renders fine for me.

![image](https://user-images.githubusercontent.com/4048809/119357889-92911f80-bc97-11eb-92eb-e70fe75a9af7.png)

2021-05-24 14:18 UTC, baltpeter commented
Let's try a hard-coded path, then.

2021-05-26 10:30 UTC, mal-tee approved these changes
Thank you, that works! They are a bit large now, but I guess that's just something to get used to.

2021-05-26 19:43 UTC, merged