WIP: Display what's left of a donation after fees, fix #386
datenanfragen/website pull request #629
Opened 2021-07-25 20:50 UTC by mal-tee

- I will need some real values for the fees :) 

- Is there a specific reason we didn't use JS' `Intl.NumberFormat` in `renderMoney` instead of `{{amount}}&nbsp;€` in our templates?

2021-07-26 13:21 UTC, baltpeter commented
>     * I will need some real values for the fees :)

* Bank transfers: free
* [CoinGate](https://coingate.com/pricing): 1%
* [PayPal](https://www.paypal.com/de/webapps/mpp/charity): 1.5% + 0.35€
* [Mollie](https://www.mollie.com/en/pricing): Depends on the method, unfortunately. :/

>     * Is there a specific reason we didn't use JS' `Intl.NumberFormat` in `renderMoney` instead of `{{amount}}&nbsp;€` in our templates?

I don't think so, feel free to change.

2021-07-26 13:33 UTC, baltpeter requested changes

2021-07-26 13:33 UTC, baltpeter commented on src/Components/DonationWidget.js
> +                                                <p style="text-align:right; margin: 0px; margin-top: -10px;">
```suggestion
                                                <p style="text-align: right; margin: -10px 0 0 0;">
```

2021-07-26 13:33 UTC, baltpeter commented on src/i18n/de.json
> +        "amount-after-fees": "Wir kriegen davon {{amount}}&nbsp;€",
I would like to make it more clear that this is due to fees as that may not be apparent to everyone. Maybe like this?

```suggestion
        "amount-after-fees": "Nach Gebühren kriegen wir {{amount}}&nbsp;€.",
```

2021-07-26 13:33 UTC, baltpeter commented on src/i18n/en.json
> +        "amount-after-fees": "We'll get {{amount}}&nbsp;€",
```suggestion
        "amount-after-fees": "After fees, we’ll get {{amount}}&nbsp;€.",
```

2021-07-26 13:33 UTC, baltpeter commented on src/Components/DonationWidget.js
> +};
The name isn't too descriptive. Maybe something like `amountAfterFees()` instead?

2021-07-26 13:33 UTC, baltpeter commented on src/Components/DonationWidget.js
> +                                                <p style="text-align:right; margin: 0px; margin-top: -10px;">
This unfortunately doesn't work well on mobile.

2021-07-26 13:33 UTC, baltpeter commented on src/Components/DonationWidget.js
> +                                                                    ) / 100
The rounding here is not necessary.

2021-07-27 08:57 UTC, zner0L commented
The CoinGate fees also depend on the current Cryptocoin price volatility, in case you want to factor that in ;P

2021-08-06 16:56 UTC, baltpeter approved these changes
Thank you!

2021-08-06 16:57 UTC, merged