Disable MailtoDropdown on template loads
datenanfragen/website pull request #675
Opened 2021-09-16 18:41 UTC by zner0L

Currently, the production tests fail because of a race condition in the template load. To prevent that, we disbale the dropdown button while the template is loading.

2021-09-16 18:56 UTC, baltpeter requested changes
Unfortunately, now other tests are failing. :/

2021-09-16 18:56 UTC, baltpeter commented on src/Components/Generator/ActionButton.js
> +            props.transport_medium === 'email' ? !!props.letter && props.ready : props.download_active && props.ready;
I personally would prefer this but that's not too important.

```suggestion
        const enabled = (props.transport_medium === 'email' ? !!props.letter : props.download_active) && props.ready;
```

2021-09-17 13:05 UTC, baltpeter requested changes
I am a little worried about `this.setState({ ready: false });` possibly happening after `this.setState({ ready: true });` as `setState()` annoyingly isn't synchronous anymore. But since it's extremely unlikely that `fetch()` finishes before the state is flushed, I consider this unlikely enough for me not to care. Just for the record. :D

2021-09-17 13:05 UTC, baltpeter commented on src/Components/RequestGeneratorBuilder.js
> +                this.setState({ ready: true });
```suggestion
                this.setState({ ready: !!text });
```

2021-09-17 13:05 UTC, baltpeter commented on src/Components/RequestGeneratorBuilder.js
> +                            this.setState({ ready: true });
```suggestion
                            this.setState({ ready: !!text });
```

2021-09-19 20:58 UTC, zner0L commented on src/Components/RequestGeneratorBuilder.js
> +                this.setState({ template_text: text, ready: true });
Will you open an issue for this?

2021-09-19 22:12 UTC, baltpeter approved these changes
Thanks! Let's hope this works…

2021-09-19 22:12 UTC, merged