Optimising deploy script to use GNU parallel
datenanfragen/website pull request #708
Opened 2021-10-02 08:33 UTC by mohitsaxenaknoldus

Fixes #674

2021-10-02 08:56 UTC, mohitsaxenaknoldus commented
I need some help fixing this Netlify thing. It says it can't find `apk`.

2021-10-02 09:10 UTC, mal-tee commented
I think we have to install that manually. @baltpeter Can you do us the honors? 

But in general we want to move the installation outside of the `deploy.sh` script. Mohit, can you please add parallel as a requirement to the README and add it to our CI config: https://github.com/datenanfragen/website/blob/master/.circleci/config.yml

2021-10-02 09:12 UTC, mal-tee commented
Can you try it again without the install-step? It might be preinstalled in netlify.

2021-10-02 09:15 UTC, mohitsaxenaknoldus commented
> Can you try it again without the install-step? It might be preinstalled in netlify.

Looks like it doesn't.

2021-10-02 09:18 UTC, mal-tee commented
Sad. CI stuff. :( That means we have to check if we are in netlify and if we are, we should obtain a binary from somewhere and just use that. Or build it ourselves in the script.

2021-10-02 09:31 UTC, mal-tee commented
I've just tested the improved script and I am quite happy:

```
# old:
./deploy.sh  218,96s user 28,39s system 191% cpu 2:09,35 total
# this PR:
./deploy.sh  221,53s user 19,38s system 250% cpu 1:36,34 total
```

2021-10-02 09:36 UTC, baltpeter requested changes
Thank you! Just some comments from me.

2021-10-02 09:36 UTC, baltpeter commented on deploy.sh
> +parallel fun ::: de en fr pt es hr
Would it be possible to use the `languages` array we have already instead of hardcoding the values again?

2021-10-02 09:36 UTC, baltpeter commented on deploy.sh
> +fun(){
Let's use a more descriptive name like `rename_for_hugo`.

2021-10-02 09:37 UTC, baltpeter commented
> I've just tested the improved script and I am quite happy:
> 
> ```
> # old:
> ./deploy.sh  218,96s user 28,39s system 191% cpu 2:09,35 total
> # this PR:
> ./deploy.sh  221,53s user 19,38s system 250% cpu 1:36,34 total
> ```

Not sure whether this will yield a noticeable improvement, but it would be nice if we could benchmark whether also parallelizing the copying of the companies and supervisory authorities is worth it.

2021-10-02 19:36 UTC, baltpeter requested changes
Thanks! Other than the comments below, if you install `parallel` in Netlify, this is good to go as far as I'm concerned.

2021-10-02 19:36 UTC, baltpeter commented on deploy.sh
> +copy_file(){
Please rename that to `copy_records`.

2021-10-02 19:36 UTC, baltpeter commented on deploy.sh
> +parallel create_directory ::: ${languages[@]}
You don't need to do that for this. Seems a little overboard for creating a couple of directories. :D

2021-10-02 19:50 UTC, mohitsaxenaknoldus commented
> Thanks! Other than the comments below, if you install `parallel` in Netlify, this is good to go as far as I'm concerned.

Resolved the comments. How can I install `parallel` in Netlify?

2021-10-02 20:08 UTC, baltpeter commented
That's unfortunately not so easy. You don't have root in the container (https://answers.netlify.com/t/apt-get-install-build-dependency/3095/2) and there doesn't seem to be a binary distribution of `parallel` (https://www.gnu.org/software/parallel/).

And compiling it each time would likely negate the benefits of using `parallel`. But you could try this:

https://git.savannah.gnu.org/cgit/parallel.git/tree/README#n84

2021-10-02 21:05 UTC, mohitsaxenaknoldus commented
> That's unfortunately not so easy. You don't have root in the container (https://answers.netlify.com/t/apt-get-install-build-dependency/3095/2) and there doesn't seem to be a binary distribution of `parallel` (https://www.gnu.org/software/parallel/).
> 
> And compiling it each time would likely negate the benefits of using `parallel`. But you could try this:
> 
> https://git.savannah.gnu.org/cgit/parallel.git/tree/README#n84

Is it not possible to install it on your Netlify runner from the backend?

2021-10-02 21:59 UTC, baltpeter commented
> Is it not possible to install it on your Netlify runner from the backend?

No.

2021-10-07 08:11 UTC, mal-tee commented
I was slightly mistaken. We need to install it manually as in the deploy-script, cause we can not install things. Did you try to acquire a binary, as @baltpeter proposed?

2021-10-07 08:25 UTC, mohitsaxenaknoldus commented
> I was slightly mistaken. We need to install it manually as in getting it in the deploy-script, cause we can not install things. Did you try to acquire a binary, as @baltpeter proposed?
> 
> > https://git.savannah.gnu.org/cgit/parallel.git/tree/README#n84

That part is done! But to install the binary we need a `dpkg` installed and for that we need to have `apk` on Netlify.

2021-10-07 11:02 UTC, mohitsaxenaknoldus commented
Ok so after adding `exit` to the loop it is now missing the `public` folder which is being ignored by the `.gitignore`.

2021-10-07 11:47 UTC, mohitsaxenaknoldus commented
> Ok so after adding `exit` to the loop it is now missing the `public` folder which is being ignored by the `.gitignore`. Is it supposed to fail at this point guys? I think we are close!

2021-10-11 11:09 UTC, mohitsaxenaknoldus commented
> > Which Ubuntu container is it using? @mal-tee @baltpeter
> 
> Seems like netlify are using 20.04 (https://github.com/netlify/build-image/blob/focal/Dockerfile)
> 
> > Ok so after adding exit to the loop it is now missing the public folder which is being ignored by the .gitignore. Is it supposed to fail at this point guys?
> 
> No.

It was missing the `public` folder due to this branch filter: `if [ "$NETLIFY" = "true" ] && [ "$BRANCH" = "master" ];`
I've fixed it now! You can re-run your performance tests again @mal-tee @baltpeter

2021-11-26 15:25 UTC, mohitsaxenaknoldus commented
> As @mal-tee said, disabling the deploy previews with Netlify is obviously not an option.
> 
> I will look at solving the Netlify problem myself on your branch. But I can't make any promises as to when that is going to happen, there's a lot of other stuff I have to do first.

Hey, were you guys able to fix it?

2021-12-01 19:17 UTC, baltpeter commented
> Hey, were you guys able to fix it?

No, unfortunately, I didn't have time for that yet.

2023-03-19 18:08 UTC, mal-tee commented
Seems like parallel is (or was?) a single perl script: https://www.gnu.org/software/parallel/parallel_design.html

2023-12-18 22:23 UTC, closed without merging