Add Croatian translation
datenanfragen/website pull request #824
Opened 2021-11-15 00:35 UTC by milotype

If necessary, please also update `template.dotx` and `template.ott`.
I don't know how to do such things ...

2021-11-25 13:09 UTC, baltpeter requested changes
Thanks, @milotype, and sorry for taking so long with the review!

I have generated the sample letters and linked them in the blog posts. There's a couple of translations that we still need. It'd be great if you could provide those as well.

2021-11-25 13:09 UTC, baltpeter commented on content/hr/blog/sample-letter-gdpr-access-request/index.md
> +<a href="/downloads/primjerak-pisma-gdpr-zahtjev-pristup-osobnipodaci.org.txt" class="button button-secondary">Download plain text file (.txt)</a>
Can you please provide translations for these strings?

* Download LibreOffice or OpenOffice template (.ott)
* Download Word template (.dotx)
* Download PDF form (.pdf)
* Download plain text file (.txt)

2021-11-25 17:14 UTC, milotype commented
@baltpeter I did the necessary changes ... I hope it's as you imagined :-)

2021-11-25 17:17 UTC, milotype commented
@baltpeter I've also noticed that some _Croatian_ filenames in **static/downloads** folder need changes!
I don't know how to change those filenames ... sorry. Below is a list of how those filenames should change. I hope you can handle that, or tell me what to do.

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/primjerak-pisma-gdpr-zahtjev-pristup-osobnipodaci.org.dotx
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-pristup-zahtjev-osobnipodaci.org.dotx

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/primjerak-pisma-gdpr-zahtjev-pristup-osobnipodaci.org.ott
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-pristup-zahtjev-osobnipodaci.org.ott

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/primjerak-pisma-gdpr-zahtjev-pristup-osobnipodaci.org.pdf
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-pristup-zahtjev-osobnipodaci.org.pdf

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/primjerak-pisma-gdpr-zahtjev-pristup-osobnipodaci.org.txt
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-pristup-zahtjev-osobnipodaci.org.txt



https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/sample-letter-gdpr-objection-request-osobnopodaci.org.dotx
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-prigovor-zahtjev-osobnopodaci.org.dotx

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/sample-letter-gdpr-objection-request-osobnopodaci.org.ott
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-prigovor-zahtjev-osobnopodaci.org.ott

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/sample-letter-gdpr-objection-request-osobnopodaci.org.pdf
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-prigovor-zahtjev-osobnopodaci.org.pdf

https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/sample-letter-gdpr-objection-request-osobnopodaci.org.txt
into
https://github.com/milotype/website-1/blob/milotype-2021-11-15/static/downloads/uzorak-pismo-gdpr-prigovor-zahtjev-osobnopodaci.org.txt

2021-12-01 19:42 UTC, baltpeter approved these changes
Thank you. :)

2021-12-01 19:43 UTC, merged