Convert DonationWidget to TypeScript
datenanfragen/website pull request #901
Opened 2022-06-01 17:54 UTC by zner0L

2022-06-04 17:01 UTC, baltpeter requested changes

2022-06-13 10:59 UTC, zner0L commented on src/Utility/common.ts
> +    Number(amount || 0).toLocaleString(window.LOCALE, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) +
Yes, `amount`has to be a `number` and guess what, `NaN` is of type `number` of course. Sadly, typescript doe not differentiate `Nan` from actual numbers (https://stackoverflow.com/questions/53999696/does-typescript-have-a-nan-type), so we need to this, even though I agree it is stupid.

2022-06-13 11:01 UTC, zner0L commented on src/Components/DonationWidget.tsx
> +    });
```suggestion
    document.querySelectorAll('.donation-widget').forEach((el) => render(<DonationWidget />, el.parentElement ?? el, el));
```

2022-06-14 10:51 UTC, baltpeter approved these changes

2022-06-14 10:56 UTC, merged