New design for our homepage
datenanfragen/website pull request #952
Opened 2022-11-04 12:47 UTC by zner0L

This is not done, yet. Currently missing:

- [ ] Working request type buttons
- [ ] Request reminder notification widget
- [ ] A "Contribute" section (do we want this?)

I would love some feedback on the current design.

2022-11-24 12:56 UTC, baltpeter submitted a review, later dismissed

2022-11-24 12:56 UTC, baltpeter commented on src/i18n/de.json
> +        "home-claim-choose-company": "Such Dir Unternehmen aus unserer Datenbank aus, oder ergänze ein eigenes. Du weiß nicht wen Du Anfragen sollst? Dann haben wir auch ein paar Vorschläge.",
```suggestion
        "home-claim-choose-company": "Such Dir Unternehmen aus unserer Datenbank aus, oder ergänze eigene. Du weiß nicht, wen Du anfragen sollst? Dann haben wir auch ein paar Vorschläge.",
```

2022-11-24 12:56 UTC, baltpeter commented on src/i18n/de.json
> +        "home-claim-react": "Im besten Fall bekommst du <strong>nach einem Monat</strong>, was du angefragt hast. Schau regelmäßig vorbei und wir erinnern Dich, falls es Zeit wird beim Unternehmen na
```suggestion
        "home-claim-react": "Im besten Fall bekommst du <em>innerhalb eines Monats</em>, was du angefragt hast. Schau regelmäßig vorbei und wir erinnern Dich, falls es Zeit wird beim Unternehmen nachzuhaken. Wir helfen dir auch, die Antworten einzuschätzen und dich ggf. zu beschweren.",
```

2022-11-30 15:44 UTC, mal-tee commented
Just chiming in with some points, I really like the current draft!

- I get a lot of JS errors on all subpages on this branch, but I guess that is already known?
- Can we add a little non-textual hint that we are talking about data **other companies** store about the user?
![image](https://user-images.githubusercontent.com/45886910/204842422-1d601971-956c-4467-97fc-ed11e4b0eda3.png)
With these buttons and headlines users could first think that this is only about data we have on them? I think we need another visual clue?
- I am not really a fan of the small margins in the 1-2-3-Box :D
- Do we intend to re-add the background-wave? Atm. the first 3/4 of the screen are very empty and vast.

2022-12-04 16:00 UTC, zner0L commented
Note to self: Apparently the reaction links are not reachable via the keyboard.

2022-12-04 16:10 UTC, zner0L commented on scripts/webpack-i18n-loader.js
> +            const property = key.reduce((obj, k) => obj?.[k], data);
I forgot for a moment that I know exactly how `data` looks like. Thanks for pointing out my stupidity!

2022-12-05 16:32 UTC, zner0L commented
Why did you break the translation in the rebase?

2022-12-05 16:51 UTC, baltpeter requested changes
Great, thanks. I'll forgive the review comments you ignored, even though I still disagree. :P

2022-12-05 16:51 UTC, baltpeter approved these changes
Oops, too many buttons.

2022-12-05 16:52 UTC, merged